# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Logging
logging.level.root=INFO

logging.level.org.hibernate=WARN
logging.level.org.springframework.data.jpa=WARN
logging.level.org.apache.coyote.http11=WARN
logging.level.org.springframework.web=WARN
logging.level.org.springframework.boot.autoconfigure=WARN

logging.level.com.dhrubok.taskmaster=INFO

logging.group.data=org.springframework.data.jpa, org.hibernate, com.zaxxer.hikari
logging.level.data=ERROR

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{20} - %msg%n
logging.file.name=logs/taskmaster.log
